### ISSUE TITLE
What is the difference between yaw_cost_function and goal_front_costs_ and alignment_costs_ 

### ISSUE THREAD

**Issue by ldm584** [GodCed/dwa_local_planner#1]
Based on my understanding of the DWA algorithm given on the official website of ROS, goal_front_costs_ and alignment_costs_ of  can realize the local trajectory to fit the global trajectory. May I ask yaw_ cost_ What are the main features of function

**Comment by GodCed** [comment]
Yaw cost aligns the robot yaw during travel with the yaw contained in the global plan poses. Original DWA local planner do not use the yaw from the global plan as it is not populated by the traditional ROS global planner.

This is useful when you want an holonomic robot to face an arbitrary direction while travelling, such as to drive sideways along an hallway so that a front facing camera looks at the wall.

**Comment by ldm584** [comment]
Thank you, but I still can't understand the difference. The following figure is a diagram that fits the global path






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GodCed/dwa_local_planner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月10日(星期天) 晚上7:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GodCed/dwa_local_planner] What is the difference between yaw_cost_function and goal_front_costs_ and alignment_costs_  (#1)





 
Yaw cost aligns the robot yaw during travel with the yaw contained in the global plan poses. Original DWA local planner do not use the yaw from the global plan as it is not populated by the traditional ROS global planner.
 
This is useful when you want an holonomic robot to face an arbitrary direction while travelling, such as to drive sideways along an hallway so that a front facing camera looks at the wall.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GodCed** [comment]
The figure didn’t came trough.

**Comment by ldm584** [comment]
Don't you see the picture? It is in the attachment, or you mean the corresponding model is not in the dwa algorithm, please excuse my confusion



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GodCed/dwa_local_planner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月11日(星期一) 凌晨0:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GodCed/dwa_local_planner] What is the difference between yaw_cost_function and goal_front_costs_ and alignment_costs_  (#1)





 
The figure didn’t came trough.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GodCed** [comment]
I don't see the picture. You can't use attachements when you reply to GitHub emails. You must go trough the GitHub website in order to add a picture to your reply.

**Comment by ldm584** [comment]
![轨迹图](https://user-images.githubusercontent.com/67676798/136804357-22474806-9792-47ed-af18-5cdf6dd75515.jpg)

**Comment by ldm584** [comment]
This is the graph I mentioned, I may have failed to understand the difference between yaw and 'distance' in the graph

**Comment by GodCed** [comment]
Yes, that is what you are missing. Here is the annotated figure with the robot and global plan poses added.

![136804357-22474806-9792-47ed-af18-5cdf6dd75515](https://user-images.githubusercontent.com/10776995/136810494-10c1b047-373f-485f-9612-7d7c54209fbc.jpg)

Please not that yaw cost would be useless with a differential robot like the one in your figure because its yaw is tied to the direction of travel. It must always face where it is going. You can think of it like a wheelbarrow.

Yaw cost is useful when the yaw is not tied to the direction of travel. You can think of it like an office chair. It can move in whatever direction while the person sitting on it looks in whatever else direction.

**Comment by ldm584** [comment]
I'm using a wheat-wheel cart, Astar algorithm for global planning, when will yaw occur regardless of the cost of travel, I can't imagine





 
---Original---
From: "Cédric ***@***.***&gt;
Date: 2021/10/11 22:50:54
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [GodCed/dwa_local_planner] What is the difference betweenyaw_cost_function and goal_front_costs_ and alignment_costs_  (#1)




 
Yes, that is what you are missing. Here is the annotated figure with the robot and global plan poses added.
 

 
Please not that yaw cost would be useless with a differential robot like the one in your figure because its yaw is tied to the direction of travel. It must always face where it is going. You can think of it like a wheelbarrow.
 
Yaw cost is useful when the yaw is not tied to the direction of travel. You can think of it like an office chair. It can move in whatever direction while the person sitting on it looks in whatever else direction.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GodCed** [comment]
I'm really not sure I understand what you are explaining, but what you need to understand is that your cart can move in whatever direction (x, y) while facing in whatever direction. Classic A-Star global planner will only provide you with a list of (x, y) points. The local planner DWA will then follow them. However, the direction the cart will be facing while it is moving along the (x, y) path is not determined because there is no cost associated to it.

Now image a scenario where there's a camera on the cart and you want it to face a wall in order to read QR codes that are on the wall. You can modify the global planner so that it now produces a list of (x, y, yaw) points. Now you need a cost function to penalize the difference between the way the cart is facing and the yaw contained in the global plan. That is what yaw_cost is.
